name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} # CRUCIAL: Asegúrate que esta variable se pasa al entorno del script
        run: |
          echo "Attempting to deploy to project ID: $RAILWAY_PROJECT_ID" # Línea de depuración
          if [ -z "$RAILWAY_PROJECT_ID" ]; then
            echo "Error: RAILWAY_PROJECT_ID is not set."
            exit 1
          fi
          railway up --detach
