name: SonarQube Analysis

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Setup Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.1.0.4889-linux-x64.zip
          unzip sonar-scanner-cli-7.1.0.4889-linux-x64.zip -d $HOME
          mv /home/runner/sonar-scanner-7.1.0.4889-linux-x64 /home/runner/sonar-scanner
          echo "$HOME/sonar-scanner/bin" >> $GITHUB_PATH

  
      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: https://c8d4-83-56-77-88.ngrok-free.app  # URL de ngrok
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=PythonWeb \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.python.version=3.11

