name: SonarQube Analysis

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # (Opcional) Instalar dependencias si las necesitas, por ejemplo para Python
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Descarga e instala sonar-scanner CLI (puedes elegir otra versión)
      - name: Setup Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-4.7.0.2747-linux.zip
          unzip sonar-scanner-*.zip -d $HOME
          mv $HOME/sonar-scanner-4.7.0.2747-linux $HOME/sonar-scanner
          echo "$HOME/sonar-scanner/bin" >> $GITHUB_PATH

      # Ejecuta el análisis
      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: https://xxxx-xxxx-1234.ngrok-free.app  # <-- tu URL de ngrok
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=PythonWeb \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
